before_install:
  - gem --version
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
  - rm -f Gemfile.lock

rvm:
  - 1.9.3
  - 2.0.0

env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 2.7.0"

matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
